### ISSUE TITLE
Always show. Feature request.

### ISSUE THREAD

**Issue by Mr-Comand** [TelepathicGrunt/StructureVoidToggle#2]
It woukld be nice to have the option to show all structure voids not only the structure voieds in the area of a structure block.

Why I need it:
I use sructure voids often to block water or place carpets ontop and not in Structures.

**Comment by TelepathicGrunt** [comment]
What Mc version are you playing on? Also I’m not sure if this will work out as if there’s a lot of structure void being drawn, the FPS will tank severely as the code Mc has for showing them is incredibly unoptimized. Someone having a ton of giant structure pieces around accidentally clicking the key and shows all the structure void may cause their game to run at a fraction of 1 fps and unable to disable it. So I would probably need to change it to show only a range of structure void close to player.

**Comment by Mr-Comand** [comment]
I'm playing on 1.19.3.

**Comment by TelepathicGrunt** [comment]
Added now for 1.19.2/3 using the DELETE key. getting the rendering to work was hell lol
